server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://shuttle.proxy.rlwy.net:45616/railway
    username: postgres
    password: ykpQMuKlLQjbMSoIHzarKgHseTtgDiGt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true